module.exports = {
  AuthorNotAuthorized: 0,
  FailedToCreateVoting: 1,
  VotingDoesNotExist: 2,
  ForbiddenForThisVotingState: 3,
  ParticipationCannotBeRevoked: 4,
  BallotCannotBeIssued: 5,
  BallotCannotBeStored: 6,
  DecryptionKeyIsAlreadyPublished: 7,
  DecryptionKeyIsNotPublished: 8,
  BallotCannotBeDecrypted: 9,
  IncorrectPrivateKey: 10,
  DecryptionIsNotFinished: 11,
  BallotDoesNotExist: 12,
  WrongTxInitiator: 13,
  VoterNotFound: 14,
  VotingAlreadyExists: 15,
  ChoicesCannotContainDuplicates: 16,
  ChoicesCannotBeLessMinChoices: 17,
  ChoicesCannotBeMoreMaxChoices: 18,
  ChoicesCannotOutOfBounds: 19,
  VoterIsNotInAcl: 20,
  VoterHasAlreadyVoted: 21,
  BallotForVoterWasAlreadyIssued: 22,
  ParticipationForVoterWasRevoked: 23,
  DistrictIDCannotBeZero: 24,
};
